### PR TITLE
feat: add `mode` options to provide scroll event

### PR DESCRIPTION
**Pull request by ron0115**
Hello, I use scrollEvent mode detect loadmore callback in my project, and it works well in IOS and Android. And how do you think about that ? 😄 We can provide the options depends on user 's need!

By the way, I am sorry for my my fault about my useless PR because I has not seen the v3.0 yet when I commit pulling request.

### CODE REVIEW

**Comment by onderonur** [comment]
This might be a very good improvement. I won't have time to check this PR for a few days, sorry. But definitely want to try it soon. Thanks for your contribution!

**Comment by onderonur** [comment]
Hi again!

First of all, sorry for the late reply. I wanted to check this PR sooner but I just got the time.

I've tried this mode. It makes a lot of sense. And thanks for usings `debounce` for improved performance. I would personally prefer throttle in such a scenario but it could be a thing to consider later.

For now, we have a little bug for this mode. 

So, let's think that a user has a huge screen or our items are just too small to fill the view. 
After the initial call, `onLoadMore` can be called by a scrolling event. 
User opens the page, an initial `useEffect` runs to check if it should run `onLoadMore`, some items are fetched/loaded. Now, user doesn't scroll, just waits. We need to call `onLoadMore` to fill user's view but it stops there and waits for user to scroll.

I've tried it like this:
I started with scroll mode on. It's like a developer wanted to use the scroll mode only.

```ts
// example\index.tsx

function App() {
  const [scrollParent, setScrollParent] = React.useState(false);
  const [scrollMode, setScrollMode] = React.useState(true); // started with true
  // ...
```
And after that, set the `ARRAY_SIZE` to `3` in `example\InfiniteList.tsx` to prevent it to fill the whole view after the initial load.
```ts
// example\InfiniteList.tsx
const ARRAY_SIZE = 3;
```
You can also set your browser's zoom like %25 etc to get this result without decreasing `ARRAY_SIZE`. It would be like we have a giant screen.

Run the demo, hit F5 to refresh, initial `onLoadMore` will be called. Items won't fill the view. Now it waits user to scroll to trigger `onLoadMore` again.

I've actually started using `setInterval` because of this kind of cases🙂 

You may also want to check resize events. Change `ARRAY_SIZE` to any value you want. Scroll and load a lot of items. Scroll to the bottom of list but don't pass the `threshold` and so it won't trigger `onLoadMore`. Now zoom out step by step. We can see bottom of the list but when we pass our `threshold` value, list should load more items. Sometimes it doesn't work. I didn't test this with your PR in a detailed way, but this was something I couldn't find a solution easily in earlier versions of this package.

If you have time to fix these cases, I would gladly try it again.

Thanks for your contribution!

**Comment by ron0115** [comment]
Hello,Sorry for my late reply.
I known what you mean at your test case.
We can have less macro tasks running and reduce perfomance of waste that's why we need scroll event mode.

To resolve the problems you'd mentioned. I set up a global state `isFull` which marks whether it is full screen at first time we init the apps.

You can checkout for more details，and look forward to your reply. Thank you so much for your code review in this PR~!😄

**Comment by onderonur** [comment]
Hi!

It's been a very long time, so I'm so sorry to reply this late.

There was a lot of different issues to make this package more "flexible". You know, it was so focused on a single use case, we would need to modify the package for each different requirement.

So, I've just published a new major version (v4). It uses `IntersectionObserver` under the hood and it has a much more flexible API.

I've just updated `README.md` too and will provide a simple migration guide in "Releases" section.

Sorry for not reviewing this PR in time. But as I said, there were a lot of different requirements and a lot of new issues were popping up regularly. So, we needed a new API 🙂.

Thanks for your effort and interest for this package!

**Pull request closed without merging**
